name: Trigger auto deployment for bitl2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/bitl2-AutoDeployTrigger-f1e8ea0d-8efe-43d0-8543-b2bb867d1b78.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BITL2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BITL2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BITL2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.BITL2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BITL2_REGISTRY_PASSWORD }}
          containerAppName: bitl2
          resourceGroup: BITL2
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


